export enum ArchitectureType {
  MONOLITHIC = 'MONOLITHIC',
  MICROSERVICE = 'MICROSERVICE',
  SERVERLESS = 'SERVERLESS',
  MICROSERVICE_MONO_REPO = 'MICROSERVICE_MONO_REPO',
  MODULAR_MONOLITH = 'MODULAR_MONOLITH',
  EVENT_DRIVEN = 'EVENT_DRIVEN',
  LAYERED = 'LAYERED',
  HEXAGONAL = 'HEXAGONAL',
  DDD = 'DDD',
}
