export declare enum Permission {
    PROJECT_VIEW = "project:view",
    PROJECT_EDIT = "project:edit",
    PROJECT_DELETE = "project:delete",
    PROJECT_MANAGE_MEMBERS = "project:manage_members",
    MODULE_VIEW = "module:view",
    MODULE_CREATE = "module:create",
    MODULE_EDIT = "module:edit",
    MODULE_DELETE = "module:delete",
    REQUIREMENT_VIEW = "requirement:view",
    REQUIREMENT_CREATE = "requirement:create",
    REQUIREMENT_EDIT = "requirement:edit",
    REQUIREMENT_DELETE = "requirement:delete",
    REQUIREMENT_REVIEW = "requirement:review",
    TASK_VIEW = "task:view",
    TASK_CREATE = "task:create",
    TASK_EDIT = "task:edit",
    TASK_DELETE = "task:delete",
    TASK_ASSIGN = "task:assign",
    BASELINE_CREATE = "baseline:create",
    BASELINE_RESTORE = "baseline:restore",
    AI_USE = "ai:use",
    ADMIN = "admin"
}
export declare enum NotificationType {
    TASK_ASSIGNED = "task_assigned",
    TASK_UPDATED = "task_updated",
    TASK_COMPLETED = "task_completed",
    REQUIREMENT_CREATED = "requirement_created",
    REQUIREMENT_REVIEW = "requirement_review",
    REQUIREMENT_APPROVED = "requirement_approved",
    REQUIREMENT_REJECTED = "requirement_rejected",
    REQUIREMENT_CHANGED = "requirement_changed",
    AI_GENERATION_COMPLETE = "ai_generation_complete",
    BASELINE_CREATED = "baseline_created",
    PROJECT_MEMBER_ADDED = "project_member_added"
}
